name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: 💾 Copy to build folder
        run: |
          rm -rf ./build/
          mkdir build
          rsync -r ./ build/ --exclude ".git" --exclude-from "./buildignore.txt"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.3
