name: 🚀 Deploy website to Strato

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: 'strato'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v3.5.3
      - name: 💾 Copy to build folder
        run: |
          rm -rf ./build/
          mkdir build
          rsync -r ./ build/ --exclude ".git" --exclude-from "./buildignore.txt"
      - name: 📂 Upload files
        uses: AbleLincoln/push-to-sftp@v2.1
        with:
          host: ssh.strato.de
          port: 22
          username: ${{ secrets.STRATO_FTP_USERNAME }}
          password: ${{ secrets.STRATO_FTP_PASSWORD }}
          sourceDir: ./build/
          targetDir: ./mxdmrt/
