name: Deploy to production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "production"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: Set up Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Upload files
        uses: AbleLincoln/push-to-sftp@v2.1
        with:
          host: ssh.strato.de
          port: 22
          username: ${{ secrets.STRATO_FTP_USERNAME }}
          password: ${{ secrets.STRATO_FTP_PASSWORD }}
          sourceDir: ./dist/
          targetDir: ./root/
