on:
  push:
    branches:
      - main
name: 🚀 Deploy website to Strato
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy website to Strato
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v3.5.3

      - name: 💾 Copy to build folder
        run: |
          rm -rf ./build/
          mkdir build
          rsync -r ./ build/ --exclude ".git" --exclude "build"

      - name: 📂 Upload files
        uses: AbleLincoln/push-to-sftp@v2.1
        with:
          host: ssh.strato.de
          port: 22
          username: ${{ secrets.STRATO_FTP_USERNAME }}
          password: ${{ secrets.STRATO_FTP_PASSWORD }}
          sourceDir: ./build/
          targetDir: ./mxdmrt/
