on: workflow_dispatch
name: 🚀 Deploy website on push
jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: deploy
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: ssh.strato.de
                  username: mad_207@maximiliandammert.com
                  password: ${{ secrets.STRATO_FTP_PASSWORD }}
                  port: 22
                  local-dir: ./test/*
                  server-dir: /
                  exclude: "[**/.git*/**, **/node_modules/**, **/build/, .babelrc, .editorconfig, .eslintrc, .prettierrc, .stylelintrc]"
                  dry-run: true
