on: push
name: 🚀 Deploy website on push
jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: deploy
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: 📂 Sync files
              uses: wlixcc/SFTP-Deploy-Action@v1.0
              with:
                  server: "ssh.strato.de"
                  username: "mad_207@maximiliandammert.com"
                  password: ${{ secrets.STRATO_FTP_PASSWORD }}
                  port: 22
                  local_path: "./static/*"
                  remote_path: "/var/www/app"
                  args: "-o ConnectTimeout=5"
