on:
  push:
    branches:
      - main
name: 🚀 Deploy website to Strato
jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: Deploy website to Strato
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: 📂 Upload files
              uses: AbleLincoln/push-to-sftp@v1.0
              with:
                  host: 'ssh.strato.de'
                  port: 22
                  username: 'mad_207@maximiliandammert.com'
                  password: ${{ secrets.STRATO_FTP_PASSWORD }}
                  sourceDir: './'
                  targetDir: '/'
