on: workflow_dispatch
name: 🚀 Deploy website on push
jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: deploy
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: 📂 Sync files
              uses: wangyucode/sftp-upload-action@v1.1
              with:
                  host: "ssh.strato.de"
                  username: "mad_207@maximiliandammert.com"
                  password: ${{ secrets.STRATO_FTP_PASSWORD }}
                  port: 22
                  localDir: "../"
                  remoteDir: "/test/"
                  args: "-o ConnectTimeout=5"
